/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-09-07 07:37:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _2_005fweaponSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>1501163</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>주무기를 선택해주세요</h3>\r\n");
      out.write("<form action =\"3_savingPage.jsp\" method=\"get\">\r\n");
 
String ctgr=request.getParameter("category");
session.setAttribute("category", ctgr);
if(ctgr.equals("ar")) {
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"m16\">M16A4<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"m4\">M416<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"scar\">SCAR-L<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"aug\">AUG<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"qbz\">QBZ<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"ak\">AKM<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"groza\">Groza<br/>\r\n");
      out.write("<input type=\"radio\" name=\"ar\" value=\"beryl\">Beryl M762<br/>\r\n");
}
if(ctgr.equals("dmr")){
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"sks\">SKS<br/>\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"vss\">VSS<br/>\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"mini\">Mini-14<br/>\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"slr\">SLR<br/>\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"mk\">Mk14<br/>\r\n");
      out.write("<input type=\"radio\" name=\"dmr\" value=\"qbu\">QBU<br/>\r\n");
}
if(ctgr.equals("sr")) {
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"sr\" value=\"kar\">Kar98k<br/>\r\n");
      out.write("<input type=\"radio\" name=\"sr\" value=\"m24\">M24<br/>\r\n");
      out.write("<input type=\"radio\" name=\"sr\" value=\"awm\">AWM<br/>\r\n");
}
if(ctgr.equals("smg")) {
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"smg\" value=\"uzi\">Micro UZI<br/>\r\n");
      out.write("<input type=\"radio\" name=\"smg\" value=\"ump\">UMP9<br/>\r\n");
      out.write("<input type=\"radio\" name=\"smg\" value=\"tommy\">Tommy Gun<br/>\r\n");
      out.write("<input type=\"radio\" name=\"smg\" value=\"vec\">Vector<br/>\r\n");
}
if(ctgr.equals("sg")) {
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"sg\" value=\"pump\">S1897<br/>\r\n");
      out.write("<input type=\"radio\" name=\"sg\" value=\"dub\">S686<br/>\r\n");
      out.write("<input type=\"radio\" name=\"sg\" value=\"saiga\">S12K<br/>\r\n");
}
if(ctgr.equals("etc")) {
      out.write("\r\n");
      out.write("<input type=\"radio\" name=\"etc\" value=\"dp\">DP-28<br/>\r\n");
      out.write("<input type=\"radio\" name=\"etc\" value=\"rambo\">M249<br/>\r\n");
      out.write("<input type=\"radio\" name=\"etc\" value=\"cross\">Crossbow<br/>\r\n");
      out.write("<input type=\"radio\" name=\"etc\" value=\"win\">Win94<br/>\r\n");
} 
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<input type=\"submit\" value=\"Subweapon\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
